spring:
  datasource:
    url: jdbc:mysql://10.36.125.200:5002/shangou_merchant_oper?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: merchant_oper
    password: merchant_oper
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:com/scut/bj/wwh/web/dao/mapper/*.xml
  type-aliases-package: com.scut.bj.wwh.web.dao
